// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/rooms": {
    params: {};
  };
  "/rooms/new": {
    params: {};
  };
  "/rooms/:roomId": {
    params: {
      "roomId": string;
    };
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/rooms" | "/rooms/new" | "/rooms/:roomId" | "/*";
  };
  "./layouts/main-layout.tsx": {
    id: "layouts/main-layout";
    page: "/" | "/rooms" | "/rooms/new" | "/rooms/:roomId";
  };
  "routes/pages/home/index.tsx": {
    id: "routes/pages/home/index";
    page: "/";
  };
  "routes/pages/rooms/index.tsx": {
    id: "routes/pages/rooms/index";
    page: "/rooms";
  };
  "routes/pages/rooms/new.tsx": {
    id: "routes/pages/rooms/new";
    page: "/rooms/new";
  };
  "routes/pages/rooms/room-detail.tsx": {
    id: "routes/pages/rooms/room-detail";
    page: "/rooms/:roomId";
  };
  "routes/not-found.tsx": {
    id: "routes/not-found";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "layouts/main-layout": typeof import("./app/./layouts/main-layout.tsx");
  "routes/pages/home/index": typeof import("./app/routes/pages/home/index.tsx");
  "routes/pages/rooms/index": typeof import("./app/routes/pages/rooms/index.tsx");
  "routes/pages/rooms/new": typeof import("./app/routes/pages/rooms/new.tsx");
  "routes/pages/rooms/room-detail": typeof import("./app/routes/pages/rooms/room-detail.tsx");
  "routes/not-found": typeof import("./app/routes/not-found.tsx");
};